version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 2000000mdc
- name: bob
  coins:
  - 10000mdc
faucet:
  name: bob
  coins:
  - 5mdc
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: mdc
  chain_id: mdc
validators:
- name: alice
  bonded: 1000000mdc
